### ISSUE TITLE
Add Configuration Options to Turn Off Default Quests

### ISSUE THREAD

**Issue by lucidobservor** [pkmnfrk/megacorp#1]
Add a mod configuration file. This file should have some properties that look something like this.

```
default-quests {
	# Should this mod load the default quests for EnderIO materials, if the mod is loaded [default: true]
	B:enderio=true
	
	# Should this mod load the default quests for Forestry materials, if the mod is loaded [default: true]
	B:forestry=true
	
	...  

	# Should this mod load the default quests for vanilla materials [default: true]
	B:vanilla=true
}
```

For each of the options, if the option is set to `true`, the corresponding quests (that mod's JSON file) will be loaded into the game. If it is set to `false`, they will not be.

**Comment by pkmnfrk** [comment]
So, rather than having individual options for each type of quest, I think I'm just going to add a blacklist. The reason is because the list of options is 1. not fixed, and 2. hopefully going to expand in the future.

But, otherwise, agreed.

**Comment by pkmnfrk** [comment]
You can blacklist by file or by id. A separate concern is that finding out the IDs of quests is non-trivial. I need to think about how to solve this, but not here.
