### ISSUE TITLE
[Suggestion] Vending machine item NBT data

### ISSUE THREAD

**Issue by slava110** [pkmnfrk/megacorp#101]
Ability to add NBT data for items in vending machine. Example:
`"items": [
{
"item": "minecraft:cookie",
"item_nbt": "{display:{Name:"Yaaay, cookie!"}}",
"amount": 15,
"cost": "12",
"cost_type": "money"
}
]`

**Comment by pkmnfrk** [comment]
I made a slight tweak to this suggestion, which is that the tag is called just "nbt", and it's full JSON. From the example:

```
{
      "item": "minecraft:diamond_sword",
      "cost": "100",
      "cost_type": "money",
      "nbt": {
        "ench": [
          {
            id: 16,
            lvl: 10
          }
        ]
      }
    }
```
