### ISSUE TITLE
[Suggestion] [Compat] [List] GameStages compat

### ISSUE THREAD

**Issue by slava110** [pkmnfrk/megacorp#104]
- [x] GameStage as quest requirement
- [x] GameStage as reward (and maybe reward requirement?)
- [x] GameStage as vending machine item requirement (player will see item in list only if has certain stage)

[Curseforge link](https://minecraft.curseforge.com/projects/game-stages)
[GameStages GitHub source link](https://github.com/Darkhax-Minecraft/Game-Stages)

**Comment by pkmnfrk** [comment]
I did the first and third items, but I will not do the second. The reason is because you can already do it using the ability to run server commands. I've documented these features here: https://github.com/pkmnfrk/megacorp/wiki/Game-Stages-Support

**Comment by pkmnfrk** [comment]
If you want to test this, please see the dev build: https://s3.amazonaws.com/pkmnfrk-minecraft-builds/pkmnfrk/megacorp/37/37.1/MegaCorp-0.2.1-37.jar

**Comment by slava110** [comment]
@pkmnfrk, yeah, I know about this feature, but I'm talking about **Capital Investor**. This buyable bonuses called rewards, right? Not quest reward, but as buyable bonus. To "buy" gamestages.
So... You can make same thing for them. Executing command. Different for every available reward rank.
P.s.: Link is broken :l

**Comment by pkmnfrk** [comment]
Ohhh, I see. I hadn't even considered that.

Yeah, okay, I can do that.

**Comment by pkmnfrk** [comment]
Oh, and sorry about the link. I use Travis CI for building these automatically, and apparently it doesn't support uploading builds for pull requests. I'm afraid I'll have to set up my own thing for this... blah.

**Comment by pkmnfrk** [comment]
Ok, I added custom rewards, which can have separate commands for each rank. See here: https://github.com/pkmnfrk/megacorp/wiki/Custom-Rewards

And, here's a preview version:
[MegaCorp-0.2.1.jar.zip](https://github.com/pkmnfrk/megacorp/files/2591253/MegaCorp-0.2.1.jar.zip)

**Comment by slava110** [comment]
**Yay**
Can I close it?
