### ISSUE TITLE
[Bug] Item still here when GUI changed

### ISSUE THREAD

**Issue by slava110** [pkmnfrk/megacorp#105]
![2018-11-16_02 35 05](https://user-images.githubusercontent.com/26705162/48588447-3c192c80-e948-11e8-95f3-0dc19607c21b.png)
![2018-11-16_02 33 05](https://user-images.githubusercontent.com/26705162/48588434-2c014d00-e948-11e8-9e93-bb318c5ac862.png)
![2018-11-16_02 33 17](https://user-images.githubusercontent.com/26705162/48588435-2e63a700-e948-11e8-8205-e0013ad68575.png)

**Comment by pkmnfrk** [comment]
This is.... not great, I agree. However, I'm not exactly sure what to do about it. Maybe I can just eject the item.

**Comment by slava110** [comment]
You can move it to player's inventory. If inventory is full - just drop it. Something like that.
