### ISSUE TITLE
Mod suggestions

### ISSUE THREAD

**Issue by Lykrast** [pkmnfrk/megacorp#12]
> If you want to suggest a mod that I can support, or find a bug, or have a neat feature idea, or if something doesn't feel right, please feel free to open an issue on GitHub:

Rather than making an issue for each popular mod I know of, here's a single one with a lot of mods grouped by theme/type. Not all of them would be an obvious fit but could be interesting to have.

Tech mods:

* [Actually Additions](https://minecraft.curseforge.com/projects/actually-additions)
* [Better With Mods](https://minecraft.curseforge.com/projects/better-with-mods)
* [Better With Addons](https://minecraft.curseforge.com/projects/better-with-addons)
* [Binnie's Mods](https://minecraft.curseforge.com/projects/binnies-mods)
* [Calculator](https://minecraft.curseforge.com/projects/calculator)
* [Deep Resonance](https://minecraft.curseforge.com/projects/deep-resonance)
* [Draconic Evolution](https://minecraft.curseforge.com/projects/draconic-evolution)
* [Embers Rekindled](https://minecraft.curseforge.com/projects/embers-rekindled)
* [Environmental Tech](https://minecraft.curseforge.com/projects/environmental-tech)
* [Factory Tech](https://minecraft.curseforge.com/projects/factory-tech)
* [Gendustry](https://minecraft.curseforge.com/projects/gendustry)
* [Immersive Engineering](https://minecraft.curseforge.com/projects/immersive-engineering)
* [Industrial Craft](https://minecraft.curseforge.com/projects/industrial-craft)
* [Industrial Foregoing](https://minecraft.curseforge.com/projects/industrial-foregoing)
* [Integrated Dynamics](https://minecraft.curseforge.com/projects/integrated-dynamics)
* [LightningCraft](https://minecraft.curseforge.com/projects/lightningcraft)
* [Magneticraft](https://minecraft.curseforge.com/projects/magneticraft)
* [Matter Overdrive: Legacy Edition](https://minecraft.curseforge.com/projects/matteroverdrive)
* [Mekanism](https://minecraft.curseforge.com/projects/mekanism) (+ [Generators](https://minecraft.curseforge.com/projects/mekanism-generators) and [Tools](https://minecraft.curseforge.com/projects/mekanism-tools))
* [NuclearCraft](https://minecraft.curseforge.com/projects/nuclearcraft-mod)
* [PneumaticCraft: Repressurized](https://minecraft.curseforge.com/projects/pneumaticcraft-repressurized)
* [Powered Thingies](https://minecraft.curseforge.com/projects/powered-thingies)
* [Prodigy Tech](https://minecraft.curseforge.com/projects/prodigy-tech)
* [Refraction](https://minecraft.curseforge.com/projects/refraction)
* [RFTools](https://minecraft.curseforge.com/projects/rftools)
* Rockhounding Mod
  * [Chemistry](https://minecraft.curseforge.com/projects/rockhounding-mod-chemistry)
  * [Ore Tiers](https://minecraft.curseforge.com/projects/rockhounding-mod-ore-tiers)
  * [Rocks](https://minecraft.curseforge.com/projects/rockhounding-mod-rocks)
  * [Surface](https://minecraft.curseforge.com/projects/rockhounding-mod-surface)
* [Rustic](https://minecraft.curseforge.com/projects/rustic)
* [Sky Resources 2](https://minecraft.curseforge.com/projects/sky-resources)
* [Soot](https://minecraft.curseforge.com/projects/soot)
* [Tech Reborn](https://minecraft.curseforge.com/projects/techreborn)
* [Techguns](https://minecraft.curseforge.com/projects/techguns)
* [Thaumcraft 6](https://minecraft.curseforge.com/projects/thaumcraft)

Magic mods with automatable parts:

* [Astral Sorcery](https://minecraft.curseforge.com/projects/astral-sorcery)
* [Blood Magic](https://minecraft.curseforge.com/projects/blood-magic)
* [Botania](https://minecraft.curseforge.com/projects/botania)
* [EvilCraft](https://minecraft.curseforge.com/projects/evilcraft)
* [Magical Crops](https://minecraft.curseforge.com/projects/magical-crops-core)
* [Mystical Agriculture](https://minecraft.curseforge.com/projects/mystical-agriculture)
* [Mystical Agradditions](https://minecraft.curseforge.com/projects/mystical-agradditions)
* [ProjectE](https://minecraft.curseforge.com/projects/projecte)
* [Wizardry](https://minecraft.curseforge.com/projects/wizardry-mod)

Dimension/exploration mods (mobs/tree farms for profit?):

* [AbyssalCraft](https://minecraft.curseforge.com/projects/abyssalcraft)
* [Aether Legacy](https://minecraft.curseforge.com/projects/aether-legacy)
* [Candy World](https://minecraft.curseforge.com/projects/candy-world)
* [Defiled Lands](https://minecraft.curseforge.com/projects/defiled-lands)
* [Electroblob's Wizardry](https://minecraft.curseforge.com/projects/electroblobs-wizardry)
* [Glacidus](https://minecraft.curseforge.com/projects/glacidus)
* [Mitsy World](https://minecraft.curseforge.com/projects/misty-world)
* [NetherEx](https://minecraft.curseforge.com/projects/netherex)
* [SugiForest](https://minecraft.curseforge.com/projects/sugiforest)
* [Terraqueous](https://minecraft.curseforge.com/projects/terraqueous)
* [The Betweenlands](https://minecraft.curseforge.com/projects/angry-pixel-the-betweenlands-mod)
* [The Erebus](https://minecraft.curseforge.com/projects/the-erebus)
* [The Midnight](https://minecraft.curseforge.com/projects/the-midnight)
* [The Twilight Forest](https://minecraft.curseforge.com/projects/the-twilight-forest)
* [Tropicraft](https://minecraft.curseforge.com/projects/tropicraft)

Mob mods (for mob farms):

* [EnergeticSheep](https://minecraft.curseforge.com/projects/energeticsheep)
* [Exotic Birds](https://minecraft.curseforge.com/projects/exotic-birds)
* [Familiar Fauna](https://minecraft.curseforge.com/projects/familiar-fauna)
* [Grimoire of Gaia](https://minecraft.curseforge.com/projects/grimoire-of-gaia)
* [Harvester's Night](https://minecraft.curseforge.com/projects/harvesters-night)
* [Headcrumbs](https://minecraft.curseforge.com/projects/headcrumbs)
* [Ice and Fire](https://minecraft.curseforge.com/projects/ice-and-fire-dragons)
* [Laser Creeper Robot Dino Riders From Space](https://minecraft.curseforge.com/projects/laser-creeper-robot-dino-riders-from-space)
* [Lycanite's Mobs](https://minecraft.curseforge.com/projects/lycanites-mobs)
* [Mowzie's Mobs](https://minecraft.curseforge.com/projects/mowzies-mobs)
* [Mystical Wildlife](https://minecraft.curseforge.com/projects/mystical-wildlife)
* [Primitive Mobs](https://minecraft.curseforge.com/projects/primitive-mobs)
* [Shadowrite](https://minecraft.curseforge.com/projects/shadowrite)
* [Trumpet Skeleton](https://minecraft.curseforge.com/projects/doot)

Dunno where to fit:

* [Cyclic](https://minecraft.curseforge.com/projects/cyclic)
* [Extra Utilities](https://minecraft.curseforge.com/projects/extra-utilities)
* [Natura](https://minecraft.curseforge.com/projects/natura)
* [OpenBlocks](https://minecraft.curseforge.com/projects/openblocks)
* [PrimalCore](https://minecraft.curseforge.com/projects/primalcore)
* [Quark](https://minecraft.curseforge.com/projects/quark)
* [Random Things](https://minecraft.curseforge.com/projects/random-things)
* [Reliquary](https://minecraft.curseforge.com/projects/reliquary-v1-3)
* [Salty Mod](https://minecraft.curseforge.com/projects/saltymod)
* [Spectrite](https://minecraft.curseforge.com/projects/spectrite-mod)
* [Tinkers Construct](https://minecraft.curseforge.com/projects/tinkers-construct)

**Comment by pkmnfrk** [comment]
Oh, wow, um... the reason for separate issues is that it makes it easier to triage and implement things piecemeal. It takes time to add unique quests for everything, you know?

Let me think about how to best go about this...

**Comment by Lykrast** [comment]
Understandable, though this was much much easier than making 84 separate issues.

**Comment by pkmnfrk** [comment]
> this was much much easier than making 84 separate issues

For you ;)

Honestly, what will probably end up happening is that I will just go down the list, examine each one, and make any that seems like it might be appropriate to add. If separate issues could be made in advance, that would speed up implementation greatly, especially if they listed what items should be added, and their relative values

**Comment by Lykrast** [comment]
I will make issues in the coming days detailling more those that I know enough about then.

May still group the mob ones together because essentially they're nothing but mob farm/animal farm fodder (for automation, if I understood your mod correctly).

**Comment by pkmnfrk** [comment]
Alright, I took the initiative to create all the issues, and bundle them into a Project: https://github.com/pkmnfrk/megacorp/projects/1

Thus, I'm going to close this, and if you're still interested, feel free to take those issues directly.
