### ISSUE TITLE
Feature: Ability to execute server commands or something

### ISSUE THREAD

**Issue by pkmnfrk** [pkmnfrk/megacorp#13]
A bunch of people asked for the ability to execute server commands. I have only a vague idea what they mean or want

**Comment by thefnitalian** [comment]
https://minecraft.gamepedia.com/Commands
I think they mean allowing to buy permission to execute admin server commands

**Comment by pkmnfrk** [comment]
I don't think that's it. I think people want to be able to execute server commands when a work order completes.

I think I will just add a setting for custom work orders so you can attach a specific command to them.
