### ISSUE TITLE
Interactions with FTB Sky Adventures

### ISSUE THREAD

**Issue by PiggyWhiskey** [pkmnfrk/megacorp#14]
With Sky Adventures v 1.1.0 and MegaCorp v 0.1.1

Can't craft the Uplink station in any crafting grid.
![image](https://user-images.githubusercontent.com/9373995/47354708-229b1100-d70b-11e8-8769-8db9da54266e.png)

Tried the following grids (In case it was an interaction error)
ProjectE Philosophers Stone
Refined Storage Crafting Grid
Tinkers Crafting Station
Vanilla Crafting Station

Also can't craft Profit Condenser or Capital Investor with the same issue (No crafting output)

**Comment by pkmnfrk** [comment]
I lied, it has nothing to do with looking at JEI. It's weird, it works right at launch, but then about 30 seconds later, it stops working. I added debugging, and it seems like at some point it stops being able to recognize the bucket (or any other fluid container I tried) as having enough fluid in it... Hmm...

**Comment by pkmnfrk** [comment]
Ok, I have a rough idea of what's actually causing this. It appears to be the Thaumic JEI addon, which seems to scan all recipes to calculate Thaumic Aspects or something. I noticed that the recipe broke at about the same time during this scan every time, and when I disabled it, the recipe never broke.

That said, I've yet to figure out what is actually breaking it. I've inspected Thaumic JEI's code, and it seems to be correct. So, this is still a mystery.

That said, I think I have a workaround that I can add. (I wouldn't necessarily call it a fix, more of a hack to sidestep what is actually breaking)

**Comment by pkmnfrk** [comment]
Ok, as is usually the case, this was actually my fault. MegaCorp adds its own fluid container that it uses to define recipes that need liquids (so you can use, eg Thermal Expansion tanks or whatever), but it was implemented slightly wrong. So, it is fixed now
