### ISSUE TITLE
Add Configuration Options to Load New Quests

### ISSUE THREAD

**Issue by lucidobservor** [pkmnfrk/megacorp#2]
Pack makers / users should be able to add their own custom quests. 

Standardize a file format (JSON, for example) in which new quests can be defined. Add a mod configuration folder, and on startup have the mod load any files with the correct extension and load those quests into the game.

As an alternative, you could allow quests to be defined and configured through ZenScript.

A README.md should be provided so users can learn how to make their own quests.

Useful error messages (as opposed to game crashes) if there is an error in the files would also be nice.

**Comment by pkmnfrk** [comment]
I took a quick glance at CraftTweaker's documentation, and found nothing for mod developers, so I decided that using the system that already exists would be a better idea.
