### ISSUE TITLE
Suggestion: Constant-rate orders

### ISSUE THREAD

**Issue by pkmnfrk** [pkmnfrk/megacorp#8]
Suggested by LucidObserver

Currently, Work Orders demand a quantity of items that scales with the level of the Work Order. It also gives higher profits based on level.

Instead, what if Work Orders had a fixed rate demand. Eg, 10 Blaze Rods per minute at $4 per item. Every time the timer runs out, a fixed number of items will be consumed, and the profit awarded. If the required number of items is not present, none of the items are consumed.

If a certain number of intervals passes without being missed, the Work Order levels up, increasing both the number of items per interval, and the amount of profit per item.

On the other hand, if the rate of missed intervals exceeds a certain threshold, then the level will decrease.

Thus, a steady supply of a given item is rewarded over bursts.

Optional features:
- Personify the performance as "Shareholders", who get happy at constant production, and unhappy at missed production.
- Add a "market", which can fluctuate and modify the prices dynamically. If in SMP, the more people who focus on a single item, the more that this depresses the price of it

**Comment by koalalord9999** [comment]
Nahh this needs to be a config option. I don't wanna play a clicker game in minecraft :P

If this were to hit main mod, and replace work orders, I would assume were the middle man in selling millions of lemonade stalls for pennies of the dollar. If you know what I mean.

As a config option, as a more passive style gameplay this would be fine I guess, but the whole randomness of work orders would be a good thing to keep.

**Comment by pkmnfrk** [comment]
A fair point. Both modes can co-exist, though, I don't need to make you choose via config.

**Comment by pkmnfrk** [comment]
This is implemented as of 7fa26f
